-- CreateEnum
CREATE TYPE "AnswerMode" AS ENUM ('CASH', 'MCQ', 'EITHER_ONE', 'TRUE_FALSE');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "allowedAnswerMode" "AnswerMode"[],
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updateAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Theme" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updateAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
